# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_calc_xpx <- function(X) {
    .Call('lmmlite_R_calc_xpx', PACKAGE = 'lmmlite', X)
}

R_eigen_decomp <- function(A) {
    .Call('lmmlite_R_eigen_decomp', PACKAGE = 'lmmlite', A)
}

R_getMLsoln <- function(hsq, Kva, y, X, reml = TRUE) {
    .Call('lmmlite_R_getMLsoln', PACKAGE = 'lmmlite', hsq, Kva, y, X, reml)
}

